definitions:
  request.UserLoginReq:
    properties:
      account:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /hello:
    get:
      produces:
      - application/json
      responses: {}
      summary: init test function
  /test:
    get:
      produces:
      - application/json
      responses: {}
      summary: used to test function
  /user/login:
    get:
      parameters:
      - description: the passed-in parameter of login function
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginReq'
      responses: {}
      summary: used to authorize user and return jwt token
swagger: "2.0"
